colectare-date/colectare-date/Controllers/AlerteController.cs
using colectare_date.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace colectare_date.Controllers
{
    public class AlerteController : Controller
    {
        private readonly AppDbContext context;

        public AlerteController(AppDbContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("admin") != "true")
                return RedirectToAction("Index", "Login");

            var colectari = await context.Colectari
                .Where(c => !c.EsteRezolvata).ToListAsync();
            var atribuiri = await context.PubeleCetateni.ToListAsync();

            var alerte = new List<dynamic>();

            foreach (var colectare in colectari)
            {
                var atribuire = atribuiri.FirstOrDefault(a => a.PubelaId == colectare.PubelaId);

                if (atribuire != null && colectare.Adresa != null &&
                    colectare.Adresa.Trim() != atribuire.Adresa.Trim())
                {
                    alerte.Add(new
                    {
                        Id = colectare.Id, 
                        PubelaId = colectare.PubelaId,
                        AdresaColectata = colectare.Adresa,
                        AdresaContract = atribuire.Adresa,
                        TimpColectare = colectare.TimpColectare
                    });
                }
            }

            return View(alerte);
        }

        [HttpPost]
        public async Task<IActionResult> RezolvareAlerta(int id)
        {
            var colectare = await context.Colectari.FindAsync(id);

            if (colectare == null)
            {
                return NotFound();
            }

            colectare.EsteRezolvata = true; 
            await context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Alerta a fost marcata ca rezolvata!";
            return RedirectToAction("Index");
        }

    }
}

colectare-date/colectare-date/Controllers/CetateanController.cs
using colectare_date.Data;
using colectare_date.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using colectare_date.ViewModels;


namespace colectare_date.Controllers
{
    public class CetateanController : Controller
    {
        private readonly AppDbContext context;

        public CetateanController(AppDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Adauga()
        {
            if (HttpContext.Session.GetString("admin") != "true")
                return RedirectToAction("Index", "Login");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Adauga(Cetatean model)
        {
            if (ModelState.IsValid)
            {
                context.Cetateni.Add(model);
                await context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Cetateanul a fost adaugat cu succes!";
                return RedirectToAction("ListaCetatenilor");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Sterge(int id)
        {
            var cetatean = await context.Cetateni.FindAsync(id);
            if (cetatean == null)
            {
                return NotFound();
            }

            context.Cetateni.Remove(cetatean);
            await context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Cetateanul a fost sters cu succes!";
            return RedirectToAction("ListaCetatenilor");
        }

        [HttpGet]
        public async Task<IActionResult> ListaCetatenilor()
        {
            if (HttpContext.Session.GetString("admin") != "true")
                return RedirectToAction("Index", "Login");

            var cetateni = await context.Cetateni.ToListAsync();
            var atribuiri = await context.PubeleCetateni.ToListAsync();
            var model = cetateni.Select(c => new CetateanCuPubeleViewModel
            {
                Cetatean = c,
                Atribuiri = atribuiri.Where(a=>a.Cetatean.Id==c.Id).ToList(),
            }).ToList();

            return View(model);
        }

        public async Task<IActionResult> Colectari(int id)
        {
            var cetatean = await context.Cetateni.FindAsync(id);

            if (cetatean == null)
                return NotFound();

            var pubeleId = await context.PubeleCetateni
                .Where(pc => pc.CetateanId == id)
                .Select(pc => pc.PubelaId)
                .ToListAsync();

            var colectari = await context.Colectari
                .Where(c => pubeleId.Contains(c.PubelaId))
                .ToListAsync();

            ViewBag.Cetatean = cetatean;
            return View(colectari);
        }

    }
}

colectare-date/colectare-date/Controllers/HartaController.cs
using colectare_date.Data;
using Microsoft.AspNetCore.Mvc;
using ClosedXML.Excel;
using colectare_date.ViewModels;
using colectare_date.Models;

namespace colectare_date.Controllers
{
    public class HartaController : Controller
    {
        private readonly AppDbContext context;

        public HartaController(AppDbContext context)
        {
            this.context = context;
        }
        public IActionResult Harta()
        {
            if (HttpContext.Session.GetString("admin") != "true")
                return RedirectToAction("Index", "Login");

            var dataCautata = new DateTime(2024, 10, 15);
            var colectari = context.Colectari
                .Where(c => c.TimpColectare.Date == dataCautata)
                .ToList();

            var rutaNeoptimizata = Enumerable.Range(0, colectari.Count + 2).ToList();
            var matrice = IncarcaMatrice();

            var rutaOptimizata = CalculeazaRutaOptimizata(matrice);

            var distantaTraseuNeoptimizat = CalculeazaDistanta(rutaNeoptimizata, matrice);
            var distantaTraseuOptimizat = CalculeazaDistanta(rutaOptimizata, matrice);

            var distantaTraseuNeoptimizatKm = distantaTraseuNeoptimizat / 1000.0;
            var distantaTraseuOptimizatKm = distantaTraseuOptimizat / 1000.0;
            var timpDeplasare = distantaTraseuOptimizatKm / 0.5;
            var timpColectare = colectari.Count * 1;
            var timpEstimativ = timpDeplasare + timpColectare;

            var model = new RutaOptimizataViewModel
            {
                Colectari = colectari,
                ColectariOptimizate = rutaOptimizata.Where(index => index > 0 && index <= colectari.Count)
                                        .Select(index => colectari[index - 1])
                                        .ToList(),
                DistantaTraseuNeoptimizat = distantaTraseuNeoptimizatKm,
                DistantaTraseuOptimizat = distantaTraseuOptimizatKm,
                DiferentaDistanta = distantaTraseuNeoptimizatKm - distantaTraseuOptimizatKm,
                TimpEstimativ = timpEstimativ
            };

            return View(model);
        }

        private int[,] IncarcaMatrice()
        {
            var caleFisier = "matrice.xlsx"; 
            using var workbook = new XLWorkbook(caleFisier);
            var ws = workbook.Worksheet("Matrix");
            int nrLinii = ws.LastRowUsed().RowNumber();
            int nrColoane = ws.LastColumnUsed().ColumnNumber();
            var matrice = new int[nrLinii, nrColoane];

            for (int i = 2; i <= nrLinii; i++) 
            {
                for (int j = 2; j <= nrColoane; j++) 
                {
                    var cellValue = ws.Cell(i, j).GetValue<double>();
                    matrice[i - 2, j - 2] = (int)Math.Round(cellValue);
                }
            }

            return matrice;
        }

        private int CalculeazaDistanta(List<int> ordine, int[,] matrice)
        {
            int distanta = 0;

            for (int i = 0; i < ordine.Count - 1; i++)
            {
                int from = ordine[i];
                int to = ordine[i + 1];
                distanta += matrice[from, to];
            }
            return distanta;
        }

        private List<int> CalculeazaRutaOptimizata(int[,] matrice)
        {
            int n = matrice.GetLength(0);
            bool[] vizitat = new bool[n];
            List<int> ruta = new List<int>();
            int current = 0;
            ruta.Add(current);
            vizitat[current] = true;

            for (int i = 1; i < n; i++)
            {
                int next = -1;
                int minDist = int.MaxValue;

                for (int j = 0; j < n; j++)
                {
                    if (!vizitat[j] && matrice[current, j] < minDist)
                    {
                        minDist = matrice[current, j];
                        next = j;
                    }
                }

                if (next != -1)
                {
                    ruta.Add(next);
                    vizitat[next] = true;
                    current = next;
                }
            }
            return ruta;
        }
    }
}

colectare-date/colectare-date/Controllers/PubelaCetateniController.cs
using colectare_date.Data;
using colectare_date.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace colectare_date.Controllers
{
    public class PubelaCetateniController : Controller
    {
        private readonly AppDbContext context;

        public PubelaCetateniController(AppDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public async Task<IActionResult> AtribuirePubela()
        {
            if (HttpContext.Session.GetString("admin") != "true")
                return RedirectToAction("Index", "Login");

            var cetateni = await context.Cetateni.ToListAsync();

            var pubeleAtribuite = await context.PubeleCetateni
                .Select(p => p.PubelaId)
                .ToListAsync();

            var pubeleDisponibile = await context.Pubele
                .Where(p => !pubeleAtribuite.Contains(p.PubelaId))
                .ToListAsync();

            if (!pubeleDisponibile.Any())
            {
                TempData["ErrorMessage"] = "Nu exista pubele disponibile pentru atribuire.";
                return RedirectToAction("ListaCetatenilor", "Cetatean");
            }

            ViewBag.Cetateni = cetateni.Select(c => new
            {
                Id = c.Id,
                NumeComplet = c.Nume + " " + c.Prenume
            }).ToList();

            ViewBag.Pubele = pubeleDisponibile;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AtribuirePubela(PubelaCetateni model)
        {
            if (!ModelState.IsValid)
            {
                TempData["ErrorMessage"] = "Datele nu sunt valide!";
            }

            if (ModelState.IsValid)
            {
                context.PubeleCetateni.Add(model);
                await context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Pubela a fost atribuita cu succes!";
                return RedirectToAction("ListaCetatenilor", "Cetatean");
            }

            var cetateni = await context.Cetateni.ToListAsync();
            var pubeleAtribuite = await context.PubeleCetateni.Select(p => p.PubelaId).ToListAsync();

            ViewBag.Cetateni = cetateni.Select(c => new
            {
                Id = c.Id,
                NumeComplet = c.Nume + " " + c.Prenume
            }).ToList();

            ViewBag.Pubele = await context.Pubele
                .Where(p => !pubeleAtribuite.Contains(p.PubelaId))
                .ToListAsync();

            return View(model);
        }
    }
}

colectare-date/colectare-date/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - colectare_date</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/colectare_date.styles.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-custom border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">colectare_date</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fas fa-home"></i> Acasa
                            </a>
                        </li>
                        @if (Context.Session.GetString("admin") != "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Login" asp-action="Index">
                                    <i class="fas fa-sign-in-alt"></i> Conectare
                                </a>
                            </li>
                        }
                        @if (Context.Session.GetString("admin") == "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Cetatean" asp-action="Adauga">
                                    <i class="fas fa-user-plus"></i> Adauga
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Cetatean" asp-action="ListaCetatenilor">
                                    <i class="fas fa-users"></i> Cetateni
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="PubelaCetateni" asp-action="AtribuirePubela">
                                    <i class="fas fa-trash"></i> Atribuie Pubela
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Harta" asp-action="Harta">
                                    <i class="fas fa-map-marked-alt"></i> Harta
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Alerte" asp-action="Index">
                                    <i class="fas fa-bell"></i> Alerte
                                </a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Login" asp-action="Logout">
                                    <i class="fas fa-sign-out-alt"></i> Deconectare
                                    </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer-custom border-top text-muted">
        <div class="container">
            <h5>PROIECT REALIZAT DE:</h5>
			<p>Ionescu Maria Magdalena si Munteanu Eduard Constantin</p>
            &copy; 2025 - colectare_date - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>