colectare-date/colectare-date/Models/Cetatean.cs
using System.ComponentModel.DataAnnotations;

namespace colectare_date.Models
{
    public class Cetatean
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Nume { get; set; }
        [Required]
        public string Prenume { get; set; }

        [Required]
        [StringLength(13,MinimumLength =13,ErrorMessage = "Un CNP valid are exact 13 caractere!")]
        public string CNP { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }
    }
}

colectare-date/colectare-date/Controllers/CetateanController.cs
using colectare_date.Data;
using colectare_date.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using colectare_date.ViewModels;


namespace colectare_date.Controllers
{
    public class CetateanController : Controller
    {
        private readonly AppDbContext context;

        public CetateanController(AppDbContext context)
        {
            this.context = context;
        }

        [HttpGet]
        public IActionResult Adauga()
        {
            if (HttpContext.Session.GetString("admin") != "true")
                return RedirectToAction("Index", "Login");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Adauga(Cetatean model)
        {
            if (ModelState.IsValid)
            {
                context.Cetateni.Add(model);
                await context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Cetateanul a fost adaugat cu succes!";
                return RedirectToAction("ListaCetatenilor");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Sterge(int id)
        {
            var cetatean = await context.Cetateni.FindAsync(id);
            if (cetatean == null)
            {
                return NotFound();
            }

            context.Cetateni.Remove(cetatean);
            await context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Cetateanul a fost sters cu succes!";
            return RedirectToAction("ListaCetatenilor");
        }

        [HttpGet]
        public async Task<IActionResult> ListaCetatenilor()
        {
            if (HttpContext.Session.GetString("admin") != "true")
                return RedirectToAction("Index", "Login");

            var cetateni = await context.Cetateni.ToListAsync();
            var atribuiri = await context.PubeleCetateni.ToListAsync();
            var model = cetateni.Select(c => new CetateanCuPubeleViewModel
            {
                Cetatean = c,
                Atribuiri = atribuiri.Where(a=>a.Cetatean.Id==c.Id).ToList(),
            }).ToList();

            return View(model);
        }

        public async Task<IActionResult> Colectari(int id)
        {
            var cetatean = await context.Cetateni.FindAsync(id);

            if (cetatean == null)
                return NotFound();

            var pubeleId = await context.PubeleCetateni
                .Where(pc => pc.CetateanId == id)
                .Select(pc => pc.PubelaId)
                .ToListAsync();

            var colectari = await context.Colectari
                .Where(c => pubeleId.Contains(c.PubelaId))
                .ToListAsync();

            ViewBag.Cetatean = cetatean;
            return View(colectari);
        }

    }
}

colectare-date/colectare-date/Views/Cetatean/Adauga.cshtml
@model colectare_date.Models.Cetatean

@{
    ViewData["Title"] = "Adauga Cetatean";
}

<div class="formular-container">
    <h2>ADAUGARE CETATEAN</h2>

    <form asp-action="Adauga" method="post">
        <div class="form-group">
            <label>Nume</label>
            <input asp-for="Nume" class="form-control" />
            <span asp-validation-for="Nume" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Prenume</label>
            <input asp-for="Prenume" class="form-control" />
            <span asp-validation-for="Prenume" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>CNP</label>
            <input asp-for="CNP" class="form-control" />
            <span asp-validation-for="CNP" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label>Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">ADAUGA</button>
    </form>
</div>

colectare-date/colectare-date/Views/Cetatean/Colectari.cshtml
@model List<colectare_date.Models.Colectare>
@{
    var cetatean = (colectare_date.Models.Cetatean)ViewBag.Cetatean;
    ViewData["Title"] = "Colectari";
}

<div class="tabel-container">
    <h2>COLECTARILE PENTRU CETATEANUL: </h2>
    <h3>@cetatean.Nume @cetatean.Prenume</h3>

    @if (!Model.Any())
    {
        <p>Acest cetatean nu are nicio colectare inregistrara.</p>
    }
    else
    {
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Pubela</th>
                    <th>Timp Colectare</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var c in Model)
                {
                    <tr>
                        <td>@c.PubelaId</td>
                        <td>@c.TimpColectare</td>
                    </tr>
                }
            </tbody>
        </table>
    }
</div>

colectare-date/colectare-date/Views/Cetatean/ListaCetatenilor.cshtml
@model IEnumerable<colectare_date.ViewModels.CetateanCuPubeleViewModel>
@{
    ViewData["Title"] = "Lista Cetatenilor";
}

<div class="tabel-container">
    <h2>LISTA CETATENILOR</h2>

    @if (TempData["SuccessMessage"] != null)
    {
        <div class="alert alert-success">@TempData["SuccessMessage"]</div>
    }

    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger">
            @TempData["ErrorMessage"]
        </div>
    }

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Nume</th>
                <th>Prenume</th>
                <th>Email</th>
                <th>CNP</th>
                <th>Pubele Atribuite </th>
                <th>Actiuni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="Cetatean" asp-action="Colectari" asp-route-id="@item.Cetatean.Id">
                                @item.Cetatean.Nume
                        </a>
                    </td>
                    <td>
                        <a asp-controller="Cetatean" asp-action="Colectari" asp-route-id="@item.Cetatean.Id">
                            @item.Cetatean.Prenume
                        </a>
                    </td>
                    <td>@item.Cetatean.Email</td>
                    <td>@item.Cetatean.CNP</td>
                    <td>
                        @if (item.Atribuiri != null && item.Atribuiri.Any())
                        {
                            <ul>
                                @foreach (var p in item.Atribuiri)
                                {
                                    <li>@p.PubelaId</li>
                                }
                            </ul>
                        }
                        else
                        {
                            <span>Nicio pubela atribuita</span>
                        }
                    </td>
                    <td>
                        <form asp-action="Sterge" asp-route-id="@item.Cetatean.Id" method="post" onsubmit="return confirm('Esti sigur ca vrei sa stergi acest cetaten?');">
                            <button type="submit" class="btn btn-danger btn-sm">Sterge</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>